name: CI

on: [push, pull_request]

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake lua5.4 libcunit1-dev
      - name: Build
        run: |
          cd generation
          sh generate.sh
          cd ..
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE ..
          make
      - name: Test
        run: |
          ./build/tests/autocorr-tests
